//
// Generated file, do not edit! Created by opp_msgtool 6.4 from messages.msg.
//

#ifndef __MESSAGES_M_H
#define __MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TempMsg;
/**
 * Class generated from <tt>messages.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet TempMsg
 * {
 *     double temperature;
 * }
 * </pre>
 */
class TempMsg : public ::omnetpp::cPacket
{
  protected:
    double temperature = 0;

  private:
    void copy(const TempMsg& other);

  protected:
    bool operator==(const TempMsg&) = delete;

  public:
    TempMsg(const char *name=nullptr, short kind=0);
    TempMsg(const TempMsg& other);
    virtual ~TempMsg();
    TempMsg& operator=(const TempMsg& other);
    virtual TempMsg *dup() const override {return new TempMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getTemperature() const;
    virtual void setTemperature(double temperature);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TempMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TempMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TempMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<TempMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGES_M_H

